ifndef WORKER
WORKER="ca"
endif
WORKER_FILE="./build/index.js"

deploy: build
ifeq ($(CA_NAME),)
	@echo "Error: CA_NAME environment variable is not found" >&2 && exit 1
endif
ifeq ($(FINGERPRINT),)
	@echo "Error: FINGERPRINT environment variable is not found" >&2 && exit 1
endif
ifeq ($(CA_URL),)
	@echo "Error: CA_URL environment variable is not found" >&2 && exit 1
endif
ifeq ($(ROOT_CA_CERT),)
	@echo "Error: ROOT_CA_CERT environment variable is not found" >&2 && exit 1
endif
	@poetry run python deploy.py \
		--name "$(CA_NAME)" \
		--fingerprint "$(FINGERPRINT)" \
		--ca-url "$(CA_URL)" \
		--root-ca "$(ROOT_CA_CERT)" \
		--worker "$(WORKER)" \
		--location "$(WORKER_FILE)"

build: clean ./worker/index.html ./worker/worker.js
	@mkdir -p ./build 
	@echo "/* This is an auto generated file. Do not edit this file */\n" > $(WORKER_FILE)
	@echo "function get_html() {\n  return \`" >> $(WORKER_FILE)
	@cat ./worker/index.html >> $(WORKER_FILE)
	@echo "\` }\n" >> $(WORKER_FILE)
	@cat ./worker/worker.js >> $(WORKER_FILE)

clean:
	@rm -rf build/
	@find . -type d -name *pycache* -exec rm -rf {} +

install: pyproject.toml
	@pip install poetry --user
	@poetry update

reset: clean
	@yes | poetry cache clear . --all > /dev/null 2>&1

.PHONY: clean build deploy install